name: .NET CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      transaction-mail-server:                                                     
        image: schickling/mailcatcher:latest
        ports:
          - "1025:1025"                                                     
          - "1080:1080"

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Ping transaction-mail-server
      run: |
        for i in {1..5}; do
          if curl --fail http://127.0.0.1:1080; then
            break
          fi
          echo "transaction-mail-server is not responding, retrying..."
          sleep 5
          if [ $i -eq 5 ]; then
            echo "transaction-mail-server failed to respond after 5 retries"
            exit 1
          fi
        done
    - name: Test
      run: dotnet test --no-restore --verbosity normal
